version: "3.8"

services:
  app:
    build: .
    container_name: "hackthon-app"
    command: sh -c "yarn knex migrate && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - hackthonDB
    depends_on:
      - hackthonDB
    environment:
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASS: postgres

  hackthonDB:
    image: postgres:alpine
    container_name: hackthon-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
